# Generated by Django 3.2.7 on 2021-09-25 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_alter_tenant_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='age',
            field=models.PositiveIntegerField(default=17),
        ),
    ]
