# Generated by Django 3.2.7 on 2021-09-20 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_alter_poll_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='poll',
            name='pub_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
