# Generated by Django 3.2.7 on 2021-10-11 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20210920_0407'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='references',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
